<?php

declare(strict_types=1);

namespace Velm\Modules\Migrations;

use Velm\Modules\ModuleSpec;
use Velm\Modules\ModuleVersion;
use Velm\Schema\SchemaAlteration;
use Velm\Schema\SchemaDiff;

final class ModuleMigrationAutogen
{
    public function migrationFilename(array $from, array $to): string
    {
        return ModuleVersion::migrationStem($from, $to).'.php';
    }

    public function renderMigration(SchemaDiff $diff, array $from, array $to): string
    {
        $fromLabel = implode('.', array_map('strval', $from));
        $toLabel = implode('.', array_map('strval', $to));
        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'use Velm\\Environment;',
            '',
            "/** Autogenerated migration {$fromLabel} → {$toLabel}. */",
            '',
            'return static function (Environment $env): void {',
        ];

        if ($diff->isEmpty()) {
            $lines[] = '    // No schema changes detected — review before shipping.';
        }

        foreach ($diff->newTables as [$table]) {
            $lines[] = "    // + table {$table}";
        }

        foreach ($diff->newColumns as [$table, $column]) {
            $lines[] = "    // + column {$table}.{$column}";
        }

        foreach ($diff->alterations as $alteration) {
            $lines[] = '    // '.$this->alterationComment($alteration);
        }

        foreach ($diff->orphanColumns as [$table, $column]) {
            $lines[] = "    // - orphan {$table}.{$column} (drop in SYNC_HOOK or here)";
        }

        if ($diff->isEmpty()) {
            $lines[] = '';
        }

        $lines[] = '};';
        $lines[] = '';

        return implode("\n", $lines);
    }

    public function bumpManifestVersion(string $manifestPath, array $from, array $to): void
    {
        $text = file_get_contents($manifestPath);

        if ($text === false) {
            throw new \RuntimeException("Could not read manifest at {$manifestPath}.");
        }

        $fromFluent = '->version('.implode(', ', $from).')';
        $toFluent = '->version('.implode(', ', $to).')';

        if (str_contains($text, $fromFluent)) {
            file_put_contents($manifestPath, str_replace($fromFluent, $toFluent, $text, $count));

            if ($count !== 1) {
                throw new \RuntimeException("Ambiguous version bump in {$manifestPath}.");
            }

            return;
        }

        $fromArray = '[\''.implode('\', \'', array_map('strval', $from)).'\']';
        $toArray = '[\''.implode('\', \'', array_map('strval', $to)).'\']';
        $patterns = [
            "'VERSION' => {$fromArray}" => "'VERSION' => {$toArray}",
            '"VERSION" => '.$fromArray => '"VERSION" => '.$toArray,
        ];

        foreach ($patterns as $search => $replace) {
            if (str_contains($text, $search)) {
                file_put_contents($manifestPath, str_replace($search, $replace, $text, $count));

                if ($count !== 1) {
                    throw new \RuntimeException("Ambiguous version bump in {$manifestPath}.");
                }

                return;
            }
        }

        throw new \RuntimeException(
            "Could not find version ".implode('.', $from)." in {$manifestPath}; bump VERSION manually.",
        );
    }

    /**
     * @param  list<int>  $current
     * @return list<int>
     */
    public function targetVersion(array $current, ?string $explicit): array
    {
        if ($explicit === null || $explicit === '') {
            return ModuleVersion::nextMinorVersion($current);
        }

        return ModuleVersion::parse($explicit);
    }

    public function write(ModuleSpec $spec, SchemaDiff $diff, array $from, array $to, bool $dryRun): string
    {
        $body = $this->renderMigration($diff, $from, $to);
        $filename = $this->migrationFilename($from, $to);
        $migrationsDir = rtrim($spec->path, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.'migrations';
        $target = $migrationsDir.DIRECTORY_SEPARATOR.$filename;
        $manifestPath = rtrim($spec->path, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.'__velm__.php';

        if ($dryRun) {
            return "# would write {$target}\n\n{$body}";
        }

        if (is_file($target)) {
            throw new \RuntimeException("Refusing to overwrite existing migration: {$target}");
        }

        if (! is_dir($migrationsDir) && ! mkdir($migrationsDir, 0775, true) && ! is_dir($migrationsDir)) {
            throw new \RuntimeException("Could not create migrations directory: {$migrationsDir}");
        }

        file_put_contents($target, $body);
        $this->bumpManifestVersion($manifestPath, $from, $to);

        return $target;
    }

    private function alterationComment(SchemaAlteration $alteration): string
    {
        return "{$alteration->table}.{$alteration->column}: {$alteration->kind} — {$alteration->detail}";
    }
}
