<?php

declare(strict_types=1);

use Velm\Environment;
use Velm\Migrations\Schema;

/** Autogenerated migration 0.2.0 → 0. */

return static function (Environment $env): void {
    // No schema changes detected — review before shipping.

};
